// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5tdM-gDAq4athlqHA7rbSgj_jiLzh7t8',
    appId: '1:1002613382326:web:cb0f1d4c5cc73d23f71a17',
    messagingSenderId: '1002613382326',
    projectId: 'quizzle-9f8e6',
    authDomain: 'quizzle-9f8e6.firebaseapp.com',
    storageBucket: 'quizzle-9f8e6.appspot.com',
    measurementId: 'G-836E2QEXP2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDaT9urTzNTthx5f6o8PcaNea3BqCIP4OE',
    appId: '1:1002613382326:android:bb8d8f2782b635bcf71a17',
    messagingSenderId: '1002613382326',
    projectId: 'quizzle-9f8e6',
    storageBucket: 'quizzle-9f8e6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFV188qH2O2UqO13Kb7MsURli-zbnvemI',
    appId: '1:1002613382326:ios:57b021802907c71af71a17',
    messagingSenderId: '1002613382326',
    projectId: 'quizzle-9f8e6',
    storageBucket: 'quizzle-9f8e6.appspot.com',
    iosBundleId: 'com.example.quizApp',
  );

}